// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHzoV_7vPOw1sVahQ_GE-bEMomC325CLY',
    appId: '1:882288873186:web:bc3fb76b60fd78333798bb',
    messagingSenderId: '882288873186',
    projectId: 'fintrack-19020',
    authDomain: 'fintrack-19020.firebaseapp.com',
    storageBucket: 'fintrack-19020.firebasestorage.app',
    measurementId: 'G-SCHENV7L71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK-2CGikc8Oi4u32oPVKmyKZddoM1ai7k',
    appId: '1:882288873186:android:9cc2ab033dd413cf3798bb',
    messagingSenderId: '882288873186',
    projectId: 'fintrack-19020',
    storageBucket: 'fintrack-19020.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ93jdHwqU7UXwXH8bmdyVwOrQeCIU4tE',
    appId: '1:882288873186:ios:993954297ee6332e3798bb',
    messagingSenderId: '882288873186',
    projectId: 'fintrack-19020',
    storageBucket: 'fintrack-19020.firebasestorage.app',
    iosBundleId: 'com.example.fintrackExpenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ93jdHwqU7UXwXH8bmdyVwOrQeCIU4tE',
    appId: '1:882288873186:ios:993954297ee6332e3798bb',
    messagingSenderId: '882288873186',
    projectId: 'fintrack-19020',
    storageBucket: 'fintrack-19020.firebasestorage.app',
    iosBundleId: 'com.example.fintrackExpenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHzoV_7vPOw1sVahQ_GE-bEMomC325CLY',
    appId: '1:882288873186:web:ecbde6c71f3131ed3798bb',
    messagingSenderId: '882288873186',
    projectId: 'fintrack-19020',
    authDomain: 'fintrack-19020.firebaseapp.com',
    storageBucket: 'fintrack-19020.firebasestorage.app',
    measurementId: 'G-X9ES97K9HC',
  );
}
